package pagesUI.user;

public class CheckoutPageUI {
	public static final String SHIPPING_SAME_ADDRESS_CHECKBOX = "//input[@id='ShipToSameAddress']";
	public static final String FIRST_NAME_TEXTBOX = "//input[@id='BillingNewAddress_FirstName']";
	public static final String LAST_NAME_TEXTBOX = "//input[@id='BillingNewAddress_LastName']";
	public static final String EMAIL_TEXTBOX = "//input[@id='BillingNewAddress_Email']";
	public static final String COUNTRY_DROPDOWNLIST = "//select[@id='BillingNewAddress_CountryId']";
	public static final String STATE_DROPDOWNLIST = "//select[@id='BillingNewAddress_StateProvinceId']";
	public static final String CITY_TEXTBOX = "//input[@id='BillingNewAddress_City']";
	public static final String FIRST_ADDRESS_TEXTBOX = "//input[@id='BillingNewAddress_Address1']";
	public static final String ZIPCODE_TEXTBOX = "//input[@id='BillingNewAddress_ZipPostalCode']";
	public static final String PHONE_NUMBER_TEXTBOX = "//input[@id='BillingNewAddress_PhoneNumber']";
	public static final String BILLING_ADDRESS_CONTINUE_BUTTON = "//div[@id='billing-buttons-container']/button[@name='save']";
	public static final String DYNAMIC_SHIPPING_METHOD_RADIO_BUTTON = "//label[text()='%s']/preceding-sibling::input";
	public static final String DYNAMIC_PAYMENT_METHOD_RADIO_BUTTON = "//label[text()='%s']/preceding-sibling::input";
	public static final String SHIPPING_METHOD_CONTINUE_BUTTON = "//div[@id='shipping-method-buttons-container']//button[text()='Continue']";
	public static final String PAYMENT_METHOD_CONTINUE_BUTTON = "//div[@id='payment-method-buttons-container']//button[@name='save']";
	public static final String PAYMENT_INFO_MESSAGE = "//div[@class='section payment-info']//td";
	public static final String PAYMENT_INFO_CONTINUE_BUTTON = "//div[@id='payment-info-buttons-container']//button[text()='Continue']";
	public static final String BILLING_NAME_VALUE = "//div[@class='billing-info']//li[@class='name']";
	public static final String BILLING_EMAIL_VALUE = "//div[@class='billing-info']//li[@class='email']";
	public static final String BILLING_PHONE_NUMBER_VALUE = "//div[@class='billing-info']//li[@class='phone']";
	public static final String BILLING_FIRST_ADDRESS_VALUE = "//div[@class='billing-info']//li[@class='address1']";
	public static final String BILLING_DETAILED_CITY_ADDRESS_VALUE = "//div[@class='billing-info']//li[@class='city-state-zip']";
	public static final String BILLING_PAYMENT_METHOD_VALUE = "//li[@class='payment-method']";
	public static final String SHIPPING_NAME_VALUE = "//div[@class='shipping-info']//li[@class='name']";
	public static final String SHIPPING_EMAIL_VALUE = "//div[@class='shipping-info']//li[@class='email']";
	public static final String SHIPPING_PHONE_NUMBER_VALUE = "//div[@class='shipping-info']//li[@class='phone']";
	public static final String SHIPPING_FIRST_ADDRESS_VALUE = "//div[@class='shipping-info']//li[@class='address1']";
	public static final String SHIPPING_DETAILED_CITY_ADDRESS_VALUE = "//div[@class='shipping-info']//li[@class='city-state-zip']";
	public static final String SHIPPING_METHOD_VALUE = "//li[@class='shipping-method']";
	public static final String BILLING_COUNTRY_VALUE = "//div[@class='billing-info']//li[@class='country']";
	public static final String SHIPPING_COUNTRY_VALUE = "//div[@class='shipping-info']//li[@class='country']";
	public static final String PRODUCT_SKU_NUMBER_VALUE = "//td[@class='sku']/span[@class='sku-number']";
	public static final String PRODUCT_IMAGE = "//td[@class='product-picture']//img";
	public static final String PRODUCT_NAME_VALUE = "//td[@class='product']//a";
	public static final String PRODUCT_UNIT_PRICE_VALUE = "//td[@class='unit-price']/span[@class='product-unit-price']";
	public static final String PRODUCT_QUANTITY_VALUE = "//td[@class='quantity']/span[@class='product-quantity']";
	public static final String PRODUCT_PRICE_VALUE = "//td[@class='subtotal']/span[@class='product-subtotal']";
	public static final String PRODUCT_GIFT_WRAPPING_VALUE = "//div[@class='cart-options']/div[@class='selected-checkout-attributes']";
	public static final String PRODUCT_SUB_TOTAL_PRICE_VALUE = "//tr[@class='order-subtotal']//span[@class='value-summary']";
	public static final String PRODUCT_SHIPPING_PRICE_VALUE = "//tr[@class='shipping-cost']//span[@class='value-summary']";
	public static final String PRODUCT_TAX_PRICE_VALUE = "//tr[@class='tax-value']//span[@class='value-summary']";
	public static final String TOTAL_PRICE_VALUE = "//tr[@class='order-total']//strong";
	public static final String PRODUCT_EARNING_POINT_VALUE = "//tr[@class='earn-reward-points']//span";
	public static final String SHIPPING_ADDRESS_DROPDOWNLIST = "//div[@class='shipping-addresses']//select[@class='address-select']";
	public static final String SHIPPING_ADDRESS_OPTIONS_IN_DROPDOWNLIST = "//div[@class='shipping-addresses']//select[@class='address-select']/option";
	public static final String SHIPPING_ADDRESS_CONTINUE_BUTTON = "//div[@id='shipping-buttons-container']//button[text()='Continue']";
	public static final String BILLING_COUNTRY_OPTIONS_IN_DROPDOWNLIST = "//select[@id='BillingNewAddress_CountryId']/option[not(text()='Select country')]";
	public static final String CONFIRM_ORDER_CONTINUE_BUTTON = "//div[@id='confirm-order-buttons-container']//button[text()='Confirm']";
	public static final String SUCCESSFUL_ORDER_MESSAGE = "//div[@class='section order-completed']//strong";
	public static final String SUCCESSFUL_ORDER_NUMBER = "//div[@class='order-number']/strong";
	public static final String CREDIT_CARD_TYPE_DROPDOWNLIST = "//select[@id='CreditCardType']";
	public static final String CARD_HOLDER_NAME_TEXTBOX = "//input[@id='CardholderName']";
	public static final String CARD_NUMBER_TEXTBOX = "//input[@id='CardNumber']";
	public static final String EXPIRE_MONTH_DROPDOWNLIST = "//select[@id='ExpireMonth']";
	public static final String EXPIRE_YEAR_DROPDOWNLIST = "//select[@id='ExpireYear']";
	public static final String CARD_CODE_TEXTBOX = "//input[@id='CardCode']";
	public static final String PAYMENT_CARD_CONTINUE_BUTTON = "//button[contains(@class,'payment-info-next-step-button')]";
	public static final String BILLING_ADDRESS_DROPDOWNLIST = "//select[@id='billing-address-select']";
	public static final String BILLING_ADDRESS_OPTIONS_IN_DROPDOWNLIST = "//select[@id='billing-address-select']/option";
	public static final String SHIPPING_FIRST_NAME_TEXTBOX = "//input[@id='ShippingNewAddress_FirstName']";
	public static final String SHIPPING_LAST_NAME_TEXTBOX = "//input[@id='ShippingNewAddress_LastName']";
	public static final String SHIPPING_EMAIL_TEXTBOX = "//input[@id='ShippingNewAddress_Email']";
	public static final String SHIPPING_COUNTRY_DROPDOWNLIST = "//select[@id='ShippingNewAddress_CountryId']";
	public static final String SHIPPING_STATE_DROPDOWNLIST = "//select[@id='ShippingNewAddress_StateProvinceId']";
	public static final String SHIPPING_CITY_TEXTBOX = "//input[@id='ShippingNewAddress_City']";
	public static final String SHIPPING_FIRST_ADDRESS_TEXTBOX = "//input[@id='ShippingNewAddress_Address1']";
	public static final String SHIPPING_ZIP_CODE_TEXTBOX = "//input[@id='ShippingNewAddress_ZipPostalCode']";
	public static final String SHIPPING_PHONE_NUMBER_TEXTBOX = "//input[@id='ShippingNewAddress_PhoneNumber']";
	public static final String BILLING_STATE_LOADING_ICON = "//select[@id='BillingNewAddress_StateProvinceId']//following-sibling::span[@id='states-loading-progress']";
	public static final String BILLING_EDIT_FORM = "//div[@class='edit-address']";
	public static final String SHIPPING_EDIT_FORM = "//div[@class='section new-shipping-address']//div[@class='edit-address']";
}
